
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Aug 28 2026 07:05:38 +07 (Aug 28 2026 00:05:38 UTC)

// Verification Directory fv/proposed_sbox_shared_affine 

module proposed_sbox_shared_affine(din, dout);
  input [4:0] din;
  output [4:0] dout;
  wire [4:0] din;
  wire [4:0] dout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_19, n_21, n_22, n_23, n_24;
  XNOR2_X1 g436__2398(.A (n_19), .B (n_24), .ZN (dout[4]));
  XNOR2_X1 g438__5107(.A (n_21), .B (n_22), .ZN (dout[3]));
  XNOR2_X1 g437__6260(.A (n_23), .B (n_24), .ZN (dout[2]));
  XOR2_X1 g440__4319(.A (n_22), .B (n_0), .Z (n_23));
  XOR2_X1 g442__8428(.A (n_14), .B (n_2), .Z (n_21));
  XNOR2_X1 g439__5526(.A (n_17), .B (n_13), .ZN (dout[1]));
  XOR2_X1 g441__6783(.A (n_15), .B (n_9), .Z (n_19));
  XNOR2_X1 g446__3680(.A (n_12), .B (n_8), .ZN (dout[0]));
  NAND2_X1 g443__1617(.A1 (n_16), .A2 (din[4]), .ZN (n_17));
  OR2_X1 g448__2802(.A1 (n_16), .A2 (n_10), .ZN (n_22));
  NOR2_X1 g444__1705(.A1 (n_16), .A2 (din[0]), .ZN (n_15));
  NAND2_X1 g445__5122(.A1 (n_16), .A2 (din[1]), .ZN (n_14));
  XOR2_X1 g447__8246(.A (n_11), .B (n_6), .Z (n_13));
  XNOR2_X1 g449__7098(.A (n_3), .B (din[4]), .ZN (n_16));
  XNOR2_X1 g452__6131(.A (n_4), .B (n_1), .ZN (n_12));
  NAND2_X1 g450__1881(.A1 (n_10), .A2 (din[0]), .ZN (n_11));
  AND2_X1 g451__5115(.A1 (n_10), .A2 (n_5), .ZN (n_9));
  NAND2_X1 g455__7482(.A1 (n_7), .A2 (din[2]), .ZN (n_8));
  NAND2_X1 g457__4733(.A1 (n_7), .A2 (din[4]), .ZN (n_24));
  XNOR2_X1 g454__6161(.A (din[1]), .B (din[2]), .ZN (n_10));
  NAND2_X1 g458__9315(.A1 (n_5), .A2 (din[3]), .ZN (n_6));
  NOR2_X1 g461__9945(.A1 (n_7), .A2 (din[0]), .ZN (n_4));
  XOR2_X1 g453__2883(.A (din[0]), .B (din[1]), .Z (n_3));
  NAND2_X1 g456__2346(.A1 (din[3]), .A2 (din[0]), .ZN (n_2));
  NAND2_X1 g459__1666(.A1 (din[4]), .A2 (din[1]), .ZN (n_1));
  NAND2_X1 g460__7410(.A1 (din[3]), .A2 (din[2]), .ZN (n_0));
  INV_X1 g462(.A (din[1]), .ZN (n_5));
  INV_X1 g463(.A (din[3]), .ZN (n_7));
endmodule

