
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Aug 28 2026 07:05:16 +07 (Aug 28 2026 00:05:16 UTC)

// Verification Directory fv/proposed_sbox_factorized 

module proposed_sbox_factorized(din, dout);
  input [4:0] din;
  output [4:0] dout;
  wire [4:0] din;
  wire [4:0] dout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_24;
  wire n_26, n_27;
  XNOR2_X1 g515__2398(.A (n_24), .B (n_9), .ZN (dout[4]));
  XNOR2_X1 g516__5107(.A (n_27), .B (n_17), .ZN (dout[2]));
  XOR2_X1 g517__6260(.A (n_26), .B (n_10), .Z (dout[1]));
  XNOR2_X1 g520__4319(.A (n_22), .B (n_12), .ZN (n_27));
  AOI22_X1 g519__8428(.A1 (n_8), .A2 (n_13), .B1 (n_14), .B2 (din[3]),
       .ZN (n_26));
  XNOR2_X1 g518__5526(.A (n_20), .B (n_21), .ZN (dout[3]));
  XNOR2_X1 g521__6783(.A (n_19), .B (n_7), .ZN (n_24));
  XNOR2_X1 g523__3680(.A (n_15), .B (n_2), .ZN (dout[0]));
  NOR2_X1 g526__1617(.A1 (n_18), .A2 (n_3), .ZN (n_22));
  XNOR2_X1 g522__2802(.A (n_4), .B (n_5), .ZN (n_21));
  NOR2_X1 g529__1705(.A1 (n_16), .A2 (din[2]), .ZN (n_20));
  NAND2_X1 g524__5122(.A1 (n_18), .A2 (n_0), .ZN (n_19));
  OR2_X1 g530__8246(.A1 (n_16), .A2 (n_11), .ZN (n_17));
  XNOR2_X1 g532__7098(.A (n_1), .B (n_6), .ZN (n_15));
  AOI21_X1 g525__6131(.A (din[1]), .B1 (n_13), .B2 (din[4]), .ZN
       (n_14));
  NAND2_X1 g527__1881(.A1 (n_11), .A2 (din[4]), .ZN (n_12));
  NAND2_X1 g528__5115(.A1 (n_11), .A2 (din[0]), .ZN (n_10));
  AND2_X1 g531__7482(.A1 (n_13), .A2 (n_11), .ZN (n_9));
  NAND2_X1 g533__4733(.A1 (n_7), .A2 (n_6), .ZN (n_8));
  OAI21_X1 g534__6161(.A (n_5), .B1 (din[2]), .B2 (din[4]), .ZN (n_18));
  INV_X1 g535(.A (n_13), .ZN (n_16));
  NAND2_X1 g538__9315(.A1 (n_3), .A2 (din[0]), .ZN (n_4));
  XOR2_X1 g537__9945(.A (din[0]), .B (din[1]), .Z (n_13));
  XNOR2_X1 g536__2883(.A (din[2]), .B (din[1]), .ZN (n_11));
  NAND2_X1 g542__2346(.A1 (n_3), .A2 (din[2]), .ZN (n_2));
  NOR2_X1 g541__1666(.A1 (n_3), .A2 (din[0]), .ZN (n_1));
  NAND2_X1 g543__7410(.A1 (n_3), .A2 (din[4]), .ZN (n_7));
  NAND2_X1 g539__6417(.A1 (din[2]), .A2 (din[4]), .ZN (n_5));
  NAND2_X1 g540__5477(.A1 (din[4]), .A2 (din[1]), .ZN (n_6));
  INV_X1 g545(.A (din[0]), .ZN (n_0));
  INV_X1 g544(.A (din[3]), .ZN (n_3));
endmodule

