
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Aug 28 2026 07:04:12 +07 (Aug 28 2026 00:04:12 UTC)

// Verification Directory fv/fides_sbox_lut 

module fides_sbox_lut(din, dout);
  input [4:0] din;
  output [4:0] dout;
  wire [4:0] din;
  wire [4:0] dout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_26, n_28, n_29, n_30, n_32;
  OAI211_X1 g725__2398(.A (n_29), .B (n_32), .C1 (n_26), .C2 (din[1]),
       .ZN (dout[2]));
  NAND2_X1 g727__5107(.A1 (n_30), .A2 (n_32), .ZN (dout[1]));
  XNOR2_X1 g726__6260(.A (n_28), .B (din[4]), .ZN (dout[3]));
  AOI221_X1 g729__4319(.A (n_23), .B1 (n_24), .B2 (din[3]), .C1 (n_18),
       .C2 (din[1]), .ZN (n_30));
  AOI211_X1 g728__8428(.A (n_4), .B (n_22), .C1 (n_7), .C2 (din[2]),
       .ZN (n_29));
  OAI221_X1 g730__5526(.A (n_2), .B1 (n_13), .B2 (din[1]), .C1 (n_17),
       .C2 (din[2]), .ZN (n_28));
  XOR2_X1 g734__6783(.A (n_26), .B (n_15), .Z (dout[4]));
  XNOR2_X1 g733__3680(.A (n_19), .B (n_24), .ZN (dout[0]));
  OAI221_X1 g731__1617(.A (n_16), .B1 (n_20), .B2 (n_14), .C1 (n_21),
       .C2 (n_12), .ZN (n_23));
  OAI22_X1 g732__2802(.A1 (n_10), .A2 (n_21), .B1 (n_20), .B2 (din[1]),
       .ZN (n_22));
  XNOR2_X1 g739__1705(.A (n_18), .B (n_17), .ZN (n_19));
  OAI21_X1 g735__5122(.A (din[2]), .B1 (n_3), .B2 (n_6), .ZN (n_16));
  AOI21_X1 g737__8246(.A (n_5), .B1 (n_14), .B2 (din[2]), .ZN (n_15));
  NOR3_X1 g738__7098(.A1 (n_8), .A2 (n_9), .A3 (n_11), .ZN (n_13));
  OR2_X1 g741__6131(.A1 (n_12), .A2 (n_11), .ZN (n_20));
  AOI21_X1 g736__1881(.A (n_9), .B1 (n_8), .B2 (din[2]), .ZN (n_10));
  INV_X1 g750(.A (n_14), .ZN (n_7));
  NAND3_X1 g744__5115(.A1 (n_11), .A2 (n_1), .A3 (din[4]), .ZN (n_32));
  INV_X1 g745(.A (n_6), .ZN (n_26));
  INV_X1 g751(.A (n_5), .ZN (n_21));
  NOR3_X1 g742__7482(.A1 (n_17), .A2 (din[2]), .A3 (din[4]), .ZN (n_4));
  NOR3_X1 g740__4733(.A1 (n_17), .A2 (din[4]), .A3 (din[1]), .ZN (n_3));
  NAND2_X1 g752__6161(.A1 (n_17), .A2 (din[0]), .ZN (n_12));
  NOR2_X1 g755__9315(.A1 (n_0), .A2 (din[4]), .ZN (n_5));
  NAND3_X1 g743__9945(.A1 (n_1), .A2 (din[2]), .A3 (din[1]), .ZN (n_2));
  NOR2_X1 g746__2883(.A1 (n_1), .A2 (n_17), .ZN (n_9));
  NOR2_X1 g749__2346(.A1 (n_17), .A2 (din[0]), .ZN (n_6));
  NOR2_X1 g754__1666(.A1 (n_1), .A2 (din[2]), .ZN (n_18));
  NAND2_X1 g753__7410(.A1 (n_0), .A2 (din[4]), .ZN (n_14));
  AND2_X1 g748__6417(.A1 (din[1]), .A2 (din[4]), .ZN (n_24));
  NOR2_X1 g747__5477(.A1 (din[3]), .A2 (din[0]), .ZN (n_8));
  INV_X1 g759(.A (din[2]), .ZN (n_11));
  INV_X1 g757(.A (din[0]), .ZN (n_1));
  INV_X1 g758(.A (din[1]), .ZN (n_0));
  INV_X1 g756(.A (din[3]), .ZN (n_17));
endmodule

