
// Generated by Cadence Genus(TM) Synthesis Solution 23.14-s090_1
// Generated on: Aug 28 2026 07:03:50 +07 (Aug 28 2026 00:03:50 UTC)

// Verification Directory fv/proposed_sbox_lut 

module proposed_sbox_lut(din, dout);
  input [4:0] din;
  output [4:0] dout;
  wire [4:0] din;
  wire [4:0] dout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_25, n_26, n_27, n_28, n_30, n_31, n_32, n_33;
  wire n_34, n_36;
  NAND2_X1 g919__2398(.A1 (n_36), .A2 (n_28), .ZN (dout[4]));
  OAI211_X1 g920__5107(.A (n_32), .B (n_4), .C1 (n_25), .C2 (n_33), .ZN
       (dout[1]));
  AOI211_X1 g921__6260(.A (n_30), .B (n_27), .C1 (n_14), .C2 (n_34),
       .ZN (n_36));
  OAI221_X1 g924__4319(.A (n_31), .B1 (n_13), .B2 (n_34), .C1 (n_12),
       .C2 (n_33), .ZN (dout[2]));
  AOI221_X1 g922__8428(.A (n_6), .B1 (n_21), .B2 (n_11), .C1 (n_26),
       .C2 (n_34), .ZN (n_32));
  AOI221_X1 g925__5526(.A (n_19), .B1 (n_15), .B2 (n_34), .C1 (n_30),
       .C2 (din[4]), .ZN (n_31));
  OAI211_X1 g923__6783(.A (n_22), .B (n_28), .C1 (n_20), .C2 (n_33),
       .ZN (dout[3]));
  OAI221_X1 g926__3680(.A (n_5), .B1 (n_16), .B2 (n_33), .C1 (n_23),
       .C2 (din[3]), .ZN (n_27));
  OAI221_X1 g927__1617(.A (n_17), .B1 (n_25), .B2 (n_3), .C1 (n_1), .C2
       (din[2]), .ZN (n_26));
  XNOR2_X1 g928__2802(.A (n_10), .B (n_23), .ZN (dout[0]));
  AOI22_X1 g929__1705(.A1 (n_21), .A2 (n_20), .B1 (n_18), .B2 (din[1]),
       .ZN (n_22));
  OAI22_X1 g930__5122(.A1 (n_18), .A2 (n_23), .B1 (n_7), .B2 (n_17),
       .ZN (n_19));
  AOI21_X1 g932__8246(.A (n_20), .B1 (n_8), .B2 (n_34), .ZN (n_16));
  NOR2_X1 g934__7098(.A1 (n_25), .A2 (n_14), .ZN (n_15));
  AOI22_X1 g933__6131(.A1 (n_14), .A2 (n_12), .B1 (din[3]), .B2
       (din[2]), .ZN (n_13));
  NOR2_X1 g936__1881(.A1 (n_11), .A2 (din[2]), .ZN (n_18));
  OAI21_X1 g940__5115(.A (n_17), .B1 (n_9), .B2 (din[3]), .ZN (n_10));
  NAND3_X1 g931__7482(.A1 (n_11), .A2 (n_34), .A3 (n_9), .ZN (n_28));
  INV_X1 g947(.A (n_17), .ZN (n_8));
  INV_X1 g946(.A (n_7), .ZN (n_21));
  NOR2_X1 g935__4733(.A1 (n_23), .A2 (din[0]), .ZN (n_6));
  NAND3_X1 g938__6161(.A1 (n_2), .A2 (n_12), .A3 (din[1]), .ZN (n_5));
  INV_X1 g948(.A (n_20), .ZN (n_25));
  NOR2_X1 g950__9315(.A1 (n_12), .A2 (n_0), .ZN (n_11));
  NOR2_X1 g952__9945(.A1 (n_12), .A2 (din[3]), .ZN (n_20));
  NAND2_X1 g951__2883(.A1 (n_12), .A2 (din[3]), .ZN (n_17));
  NAND3_X1 g937__2346(.A1 (din[0]), .A2 (din[1]), .A3 (din[2]), .ZN
       (n_4));
  INV_X1 g941(.A (n_14), .ZN (n_3));
  NAND2_X1 g949__1666(.A1 (n_2), .A2 (din[2]), .ZN (n_7));
  NOR3_X1 g939__7410(.A1 (din[3]), .A2 (din[0]), .A3 (din[2]), .ZN
       (n_30));
  NOR2_X1 g943__6417(.A1 (din[4]), .A2 (din[2]), .ZN (n_14));
  NAND2_X1 g944__5477(.A1 (din[4]), .A2 (din[2]), .ZN (n_33));
  NAND2_X1 g942__2398(.A1 (din[4]), .A2 (din[3]), .ZN (n_1));
  NAND2_X1 g945__5107(.A1 (din[4]), .A2 (din[1]), .ZN (n_23));
  INV_X1 g954(.A (din[2]), .ZN (n_9));
  INV_X1 g956(.A (din[0]), .ZN (n_12));
  INV_X1 g955(.A (din[3]), .ZN (n_0));
  INV_X1 g953(.A (din[4]), .ZN (n_2));
  INV_X1 g957(.A (din[1]), .ZN (n_34));
endmodule

